name: Comment Pull Request
on:
  workflow_run:
    workflows: ["Pull Request"]
    types: [completed]
permissions:
  pull-requests: write
jobs:
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: process
      - name: Comment on PR
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var issueNumber = Number(fs.readFileSync('pr.txt'));
            var message = fs.readFileSync('message.txt').toString();
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });
