name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
#      - name: Check fork
#        if: github.event.pull_request.head.repo.full_name != github.repository
#        uses: actions/github-script@v6.4.1
#        with:
#          script: |
#            await github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: 'Do not create pull requests from forks!'
#            })
#            await github.rest.issues.update({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              state: 'closed'
#            })
#            process.exit(1);
      - name: Checkout
        uses: actions/checkout@v3.5.1
#        with:
#          ref: ${{github.head_ref}}
      - name: Process
        run: |
          mkdir -p output
          echo ${{github.event.number}} > output/pr.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: process
          path: output/
