name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
#        with:
#          ref: ${{github.head_ref}}
      - name: Setup Java JDK
#         uses: actions/setup-java@v3.9.0
#         with:
#           distribution: oracle
#           java-version: 20
        uses: oracle-actions/setup-java@b9d8cf728e941b3ce91823c84cb792e7602e4687
      - name: Process
        run: |
          mkdir -p artifact
          echo ${{github.event.number}} > artifact/pr.txt
          set +e
          bash tools/build.sh process
          echo "EXIT_CODE=$?" >> $GITHUB_ENV
          cat "out/message.txt" 1> artifact/message.txt
          [ -s artifact/message.txt ] || {
            echo -e "\u2757 Seems like there are no changes in jetbrains.api." > artifact/message.txt
            echo "EXIT_CODE=1" >> $GITHUB_ENV
          }
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: process
          path: artifact/
      - name: Check exit code
        run: |
          test $EXIT_CODE -eq 0 || exit 1
