name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
#        with:
#          ref: ${{github.head_ref}}
      - name: Process
        run: |
          mkdir -p output
          echo ${{github.event.number}} > output/pr.txt
          git status > output/message.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: process
          path: output/
