name: Push
on:
  push:
    branches: [main]
permissions:
  contents: write
env:
  ACCESS_EMAIL: ${{secrets.ACCESS_EMAIL}}
jobs:
  update-api:
    if: github.event.pusher.email != '${{env.ACCESS_EMAIL}}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
      - name: Setup Java JDK
#         uses: actions/setup-java@v3.9.0
#         with:
#           distribution: oracle
#           java-version: 20
        uses: oracle-actions/setup-java@b9d8cf728e941b3ce91823c84cb792e7602e4687
      - name: Build
        id: build
        run: |
          bash tools/build.sh full
          [ -s out/message.txt ] || {
            echo "Seems like there are no changes in jetbrains.api."
            exit 0
          }
          API_VERSION="`cat out/version.txt`"
          echo "API version: $API_VERSION"
          [[ "$API_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
            echo "API version looks incorrect."
            exit 1
          }
          \cp out/api-blob .
          git add api-blob
          git config --global user.name 'JBR API'
          git config --global user.email '${{secrets.ACCESS_EMAIL}}'
          git commit -m "v$API_VERSION"
          git push
          echo "SUCCESS=true" >> "$GITHUB_OUTPUT"
      - name: Test
        if: ${{steps.build.outputs.SUCCESS}}
        run: |
          echo "ABOBA"
