name: Update API
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Override API version'
        required: false
        default: ''
        type: string
permissions:
  contents: write
jobs:
  update-api:
    if: github.event.pusher.email != vars.PUSH_EMAIL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
      - name: Setup Java JDK
#         uses: actions/setup-java@v3.9.0
#         with:
#           distribution: oracle
#           java-version: 20
        uses: oracle-actions/setup-java@b9d8cf728e941b3ce91823c84cb792e7602e4687
      - name: Build
        id: build
        run: |
          bash tools/build.sh ${{ inputs.version != '' && inputs.version || 'full' }}
          MESSAGE="`cat out/message.txt`"
          if [ "x$MESSAGE" = "x" ] ; then
            echo "Seems like there are no changes in jetbrains.api."
            exit 0
          fi
          API_VERSION="`cat out/version.txt`"
          echo "API version: $API_VERSION"
          [[ "$API_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
            echo "API version looks incorrect."
            exit 1
          }
          API_DIFF=${MESSAGE#*\`\`\`}
          API_DIFF=${API_DIFF%\`\`\`*}
          [[ "$MESSAGE" = "$API_DIFF" ]] && API_DIFF=""
          \cp out/api-blob .
          git add api-blob
          git config --global user.name 'JBR API'
          git config --global user.email '${{vars.PUSH_EMAIL}}'
          set +e
          git commit -m "v$API_VERSION" -m "$API_DIFF"
          git tag -a "v$API_VERSION" -m "v$API_VERSION
          
          $API_DIFF"
          set -e
          git push --tags
          echo "SUCCESS=true" >> "$GITHUB_OUTPUT"
      - name: Test
        if: ${{steps.build.outputs.SUCCESS}}
        run: |
          echo "ABOBA"
